---
- name: Check {{ storage.longhorn }} exist
  become: yes
  file:
    path: '{{ storage.longhorn }}'
    state: directory
    owner: root
    group: root

- name: Check {{ storage.nfs_provisioner }} exist
  become: yes
  file:
    path: '{{ storage.nfs_provisioner }}'
    state: directory
    owner: root
    group: root