---
- name: Create "{{ apps.argocd.namespace }}" namespace
  k8s:
    name: "{{ apps.argocd.namespace }}"
    kind: Namespace
    state: present
  delegate_to: localhost

# TODO: Enable admin user - modify line 223 - homelab-pi-k3s/platform/argocd/values.yaml

- name: Deploy ArgoCD
  shell: |
    helm dependency build &&
    helm template "{{ apps.argocd.name }}" --include-crds --namespace "{{ apps.argocd.namespace }}" . > resources/all.yaml &&
    kubectl apply -k .
  args:
    chdir: "{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s/platform/argocd/"
  delegate_to: localhost

- name: Pause 1 minutes to deploy argocd
  pause:
    minutes: 1

- name: Wait for argocd pods to be running
  shell: kubectl get pods -n argocd -o json
  register: kubectl_get_pods_argocd
  until: kubectl_get_pods_argocd.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  delegate_to: localhost
  retries: 10
  delay: 30

- name: Add calico deploy to argocd
  k8s:
    state: present
    src: "{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s/platform/argocd/apps/calico.yaml"
  delegate_to: localhost
