---
- name: Create "{{ apps.arr.namespace }}" namespace
  k8s:
    name: "{{ apps.arr.namespace }}"
    kind: Namespace
    state: present
  delegate_to: localhost

- name: Restore arr apps volume backup from longhorn
  uri:
    url: https://longhorn.local.tecno-fly.com/v1/volumes
    method: POST
    body: '{"name":"{{ item.volume_name }}","numberOfReplicas":3,"accessMode":"rwo","encrypted":false,"nodeSelector":[],"diskSelector":[],"fromBackup":"s3://longhorn-backups@us-east-1/?backup={{ item.backup_id }}&volume={{ item.volume_name }}","staleReplicaTimeout":20}'
    body_format: json
    validate_certs: false
  delegate_to: localhost
  with_items: "{{ apps.arr.volumes }}"

- name: Pause 2 minutes to restore bazarr volume backup
  pause:
    minutes: 2

- name: Create PV arr apps
  uri:
    url: "https://longhorn.local.tecno-fly.com/v1/volumes/{{ item.volume_name }}?action=pvCreate"
    method: POST
    body: '{"pvName":"{{ item.volume_name }}","fsType":"ext4"}'
    body_format: json
    validate_certs: false
  delegate_to: localhost
  with_items: "{{ apps.arr.volumes }}"

- name: Create PVC arr apps
  uri:
    url: "https://longhorn.local.tecno-fly.com/v1/volumes/{{ item.volume_name }}?action=pvcCreate"
    method: POST
    body: '{"namespace":"{{ apps.arr.namespace }}","pvcName":"{{ item.pvc_name }}"}'
    body_format: json
    validate_certs: false
  delegate_to: localhost
  with_items: "{{ apps.arr.volumes }}"

- name: Deploy arr applications
  k8s:
    state: present
    src: "{{ item }}"
  with_items:
    - '{{playbook_dir}}/k3s-apps-install/files/argocd-homelab-pi-k3s/apps/arr/project/arr.yaml'
    - '{{playbook_dir}}/k3s-apps-install/files/argocd-homelab-pi-k3s/apps/arr/application/arr.yaml'
  delegate_to: localhost

- name: Pause 30 seconds to deploy arr apps
  pause:
    seconds: 30

- name: Wait for arr pods to be running
  shell: kubectl get pods -n arr -o json
  register: kubectl_get_pods_arr
  until: kubectl_get_pods_arr.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  delegate_to: localhost
  retries: 20
  delay: 60