---
- name: Deploy radarr
  k8s:
    state: present
    src: "{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s/platform/argocd/apps/arr.yaml"
  delegate_to: localhost

- name: Pause 30 seconds to deploy arr apps
  pause:
    seconds: 30

- name: Wait for arr pods to be running
  shell: kubectl get pods -n arr -o json
  register: kubectl_get_pods_arr
  until: kubectl_get_pods_arr.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  delegate_to: localhost
  retries: 10
  delay: 30