---
- name: Remove repo
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - '{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s'
    - '{{playbook_dir}}/k3s-apps-install/files/argocd-homelab-pi-k3s'
  delegate_to: localhost