---
- name: Deploy external-endpoints
  k8s:
    state: present
    src: "{{ item }}"
  with_items:
    - '{{playbook_dir}}/k3s-apps-install/files/argocd-homelab-pi-k3s/apps/external-endpoints/project/external-endpoints.yaml'
    - '{{playbook_dir}}/k3s-apps-install/files/argocd-homelab-pi-k3s/apps/external-endpoints/application/external-endpoints.yaml'
  delegate_to: localhost
