---
- name: Deploy gitea
  k8s:
    state: present
    src: "{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s/platform/argocd/apps/gitea.yaml"
  delegate_to: localhost

- name: Pause 30 seconds to deploy gitea
  pause:
    seconds: 30

- name: Wait for gitea pods to be running
  shell: kubectl get pods -n gitea -o json
  register: kubectl_get_pods_gitea
  until: kubectl_get_pods_gitea.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  delegate_to: localhost
  retries: 10
  delay: 30