---
- name: Deploy home-assistant
  k8s:
    state: present
    src: "{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s/platform/argocd/apps/home-assistant.yaml"
  delegate_to: localhost

- name: Pause 30 seconds to deploy home-assistant
  pause:
    seconds: 30

- name: Wait forhome-assistant pods to be running
  shell: kubectl get pods -n home-assistant -o json
  register: kubectl_get_pods_home_assistant
  until: kubectl_get_pods_home_assistant.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  delegate_to: localhost
  retries: 10
  delay: 30