---
- name: Create "{{ apps.home_assistant.namespace }}" namespace
  k8s:
    name: "{{ apps.home_assistant.namespace }}"
    kind: Namespace
    state: present
  delegate_to: localhost

- name: Get list of home-assistant volume backups
  uri:
    url: "{{ apps.longhorn.base_url }}/v1/backupvolumes/{{ apps.home_assistant.volume_name }}?action=backupList"
    method: POST
    validate_certs: false
  register: backup_list
  delegate_to: localhost
  
  # Get latest backup
- set_fact:
    backup_id: "{{ backup_list | json_query('json.data[*].{created: created, id: id}') | sort(attribute='created') | reverse | json_query('[0].id') }}"

- name: Restore home-assistant volume backup from longhorn
  uri:
    url: "{{ apps.longhorn.base_url }}/v1/volumes"
    method: POST
    body: '{"name":"{{ apps.home_assistant.volume_name }}","numberOfReplicas":3,"accessMode":"rwo","encrypted":false,"nodeSelector":[],"diskSelector":[],"fromBackup":"s3://longhorn-backups@us-east-1/?backup={{ backup_id }}&volume={{ apps.home_assistant.volume_name }}","staleReplicaTimeout":20}'
    body_format: json
    validate_certs: false
  delegate_to: localhost

- name: Pause 1 minutes to restore home-assistant volume backup
  pause:
    minutes: 1
  delegate_to: localhost
  
- name: Create PV home-assistant
  uri:
    url: "https://longhorn.local.tecno-fly.com/v1/volumes/{{ apps.home_assistant.volume_name }}?action=pvCreate"
    method: POST
    body: '{"pvName":"{{ apps.home_assistant.volume_name }}","fsType":"ext4"}'
    body_format: json
    validate_certs: false
  delegate_to: localhost
  
- name: Create PVC home-assistant
  uri:
    url: "https://longhorn.local.tecno-fly.com/v1/volumes/{{ apps.home_assistant.volume_name }}?action=pvcCreate"
    method: POST
    body: '{"namespace":"{{ apps.home_assistant.namespace }}","pvcName":"{{ apps.home_assistant.pvc_name }}"}'
    body_format: json
    validate_certs: false
  delegate_to: localhost
  
- name: Deploy home-assistant
  k8s:
    state: present
    src: "{{ item }}"
  with_items:
    - '{{playbook_dir}}/k3s-apps-install/files/argocd-homelab-pi-k3s/apps/home-assistant/project/home-assistant.yaml'
    - '{{playbook_dir}}/k3s-apps-install/files/argocd-homelab-pi-k3s/apps/home-assistant/application/home-assistant.yaml'
  delegate_to: localhost
  
- name: Pause 30 seconds to deploy home-assistant
  pause:
    seconds: 30
  delegate_to: localhost
  
- name: Wait for home-assistant pods to be running
  shell: kubectl get pods -n home-assistant -o json
  register: kubectl_get_pods_home_assistant
  until: kubectl_get_pods_home_assistant.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  retries: 20
  delay: 60
  delegate_to: localhost
  