---
- name: Disable ingress-nginx metrics until prometheus is deployed
  lineinfile:
    dest: "{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s/system/ingress-nginx/values.yaml"
    regexp: "^(\\s*)enabled:.*"
    line: '\1enabled: false'
    firstmatch: true
    backrefs: true
    state: present
  delegate_to: localhost

- name: Disable ingress-nginx metrics until prometheus is deployed
  lineinfile:
    dest: "{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s/system/ingress-nginx/kustomization.yaml"
    regexp: "{{ item }}"
    line: "#{{ item }}"
    state: present
  with_items:
    - '- ./resources/prometheus-rules.yaml'
  delegate_to: localhost

- name: Commit ingress-nginx changes to repository
  shell: |
    git add values.yaml &&
    git add kustomization.yaml &&
    git commit -m "[Ansible] ingress-nginx - Temporary disabled metrics" &&
    git push
  args:
    chdir: "{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s/system/ingress-nginx"
  ignore_errors: true
  delegate_to: localhost

- name: Deploy ingress-nginx
  k8s:
    state: present
    src: "{{ item }}"
  with_items:
    - '{{playbook_dir}}/k3s-apps-install/files/argocd-homelab-pi-k3s/system/ingress-nginx/project/ingress-nginx.yaml'
    - '{{playbook_dir}}/k3s-apps-install/files/argocd-homelab-pi-k3s/system/ingress-nginx/application/ingress-nginx.yaml'
  delegate_to: localhost

- name: Pause 30 seconds to deploy ingress-nginx
  pause:
    seconds: 30

- name: Wait for ingress-nginx pods to be running
  shell: kubectl get pods -n ingress-nginx -o json
  register: kubectl_get_pods_ingress_nginx
  until: kubectl_get_pods_ingress_nginx.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  delegate_to: localhost
  retries: 10
  delay: 30
