---
- name: Deploy k8tz
  k8s:
    state: present
    src: "{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s/platform/argocd/apps/k8tz.yaml"
  delegate_to: localhost

- name: Pause 1 minutes to deploy k8tz
  pause:
    minutes: 1

- name: Wait for k8tz pods to be running
  shell: kubectl get pods -n k8tz -o json
  register: kubectl_get_pods_k8tz
  until: kubectl_get_pods_k8tz.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  delegate_to: localhost
  retries: 10
  delay: 30