---
- name: Create "{{ apps.longhorn.namespace }}" namespace
  k8s:
    name: "{{ apps.longhorn.namespace }}"
    kind: Namespace
    state: present
  delegate_to: localhost

- name: Create secret
  template:
    src: "templates/longhorn-backup-target-credential-secret.yaml.j2"
    dest: "{{playbook_dir}}/k3s-apps-install/files/longhorn-backup-target-credential-secret.yaml"
    mode: 0644
  delegate_to: localhost

- name: Apply secret
  k8s:
    state: present
    src: "{{playbook_dir}}/k3s-apps-install/files/longhorn-backup-target-credential-secret.yaml"
  delegate_to: localhost

# TODO: Comment line 4 on homelab-pi-k3s/system/longhorn-system/kustomization.yaml

- name: Deploy longhorn
  k8s:
    state: present
    src: "{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s/platform/argocd/apps/longhorn-no-vault.yaml"
  delegate_to: localhost

- name: Pause 1 minutes to deploy longhorn
  ansible.builtin.pause:
    minutes: 1

- name: Wait for longhorn pods to be running
  shell: kubectl get pods -n longhorn-system -o json
  register: kubectl_get_pods_longhorn
  until: kubectl_get_pods_longhorn.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  delegate_to: localhost
  retries: 10
  delay: 30