---
- name: Deploy metallb
  k8s:
    state: present
    src: "{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s/platform/argocd/apps/metallb.yaml"
  delegate_to: localhost

- name: Pause 30 seconds to deploy metallb
  pause:
    seconds: 30

- name: Wait for metallb pods to be running
  shell: kubectl get pods -n metallb-system -o json
  register: kubectl_get_pods_metallb
  until: kubectl_get_pods_metallb.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  delegate_to: localhost
  retries: 10
  delay: 30