---
- name: Deploy kube-prometheus-stack
  k8s:
    state: present
    src: "{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s/platform/argocd/apps/monitoring-prometheus-stack.yaml"
  delegate_to: localhost

- name: Pause 60 seconds to deploy kube-prometheus-stack
  pause:
    seconds: 60

- name: Wait for kube-prometheus-stack pods to be running
  shell: kubectl get pods -n monitoring-system -o json
  register: kubectl_get_pods_kube_prometheus_stack
  until: kubectl_get_pods_kube_prometheus_stack.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  delegate_to: localhost
  retries: 10
  delay: 30

- name: Deploy loki
  k8s:
    state: present
    src: "{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s/platform/argocd/apps/monitoring-loki.yaml"
  delegate_to: localhost

- name: Pause 30 seconds to deploy loki
  pause:
    seconds: 30

- name: Wait for loki pods to be running
  shell: kubectl get pods -n monitoring-system -o json
  register: kubectl_get_pods_loki
  until: kubectl_get_pods_loki.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  delegate_to: localhost
  retries: 10
  delay: 30

- name: Deploy monitoring-extras
  k8s:
    state: present
    src: "{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s/platform/argocd/apps/monitoring-extras.yaml"
  delegate_to: localhost

- name: Pause 30 seconds to deploy monitoring-extras
  pause:
    seconds: 30

- name: Wait for monitoring-extras pods to be running
  shell: kubectl get pods -n monitoring-system -o json
  register: kubectl_get_pods_monitoring_extras
  until: kubectl_get_pods_monitoring_extras.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  delegate_to: localhost
  retries: 10
  delay: 30

- name: Patch calico FelixConfiguration to activate metrics
  shell: "kubectl patch felixconfiguration default --type merge --patch '{\"spec\":{\"prometheusMetricsEnabled\": true}}'"
  delegate_to: localhost

- name: Patch service calico-kube-controllers-metrics
  shell: "kubectl patch svc calico-kube-controllers-metrics -n calico-system -p '{\"metadata\":{\"annotations\":{\"prometheus.io/port\": \"9094\",\"prometheus.io/scrape\": \"true\"}}}'"
  delegate_to: localhost

- name: Deploy calico-metrics
  k8s:
    state: present
    src: "{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s/platform/argocd/apps/calico-metrics.yaml"
  delegate_to: localhost