---
- name: Deploy nfs-provisioner
  k8s:
    state: present
    src: "{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s/platform/argocd/apps/nfs-provisioner.yaml"
  delegate_to: localhost

- name: Pause 30 seconds to deploy nfs-provisioner
  pause:
    seconds: 30

- name: Wait for nfs-provisioner pods to be running
  shell: kubectl get pods -n nfs-provisioner -o json
  register: kubectl_get_pods_nfs_provisioner
  until: kubectl_get_pods_nfs_provisioner.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  delegate_to: localhost
  retries: 10
  delay: 30