---
- name: Create "{{ apps.vault.namespace }}" namespace
  k8s:
    name: "{{ apps.vault.namespace }}"
    kind: Namespace
    state: present
  delegate_to: localhost

- name: Restore vault volume backup from longhorn
  uri:
    url: https://longhorn.local.tecno-fly.com/v1/volumes
    method: POST
    body: '{"name":"{{ apps.vault.volume_name }}","numberOfReplicas":3,"accessMode":"rwo","encrypted":false,"nodeSelector":[],"diskSelector":[],"fromBackup":"s3://longhorn-backups@us-east-1/?backup={{ apps.vault.backup_id }}&volume={{ apps.vault.volume_name }}","staleReplicaTimeout":20}'
    body_format: json
    validate_certs: false
  delegate_to: localhost

- name: Pause 1 minutes to restore vault volume backup
  pause:
    minutes: 1

- name: Create PV vault
  uri:
    url: "https://longhorn.local.tecno-fly.com/v1/volumes/{{ apps.vault.volume_name }}?action=pvCreate"
    method: POST
    body: '{"pvName":"{{ apps.vault.volume_name }}","fsType":"ext4"}'
    body_format: json
    validate_certs: false
  delegate_to: localhost

- name: Create PVC vault
  uri:
    url: "https://longhorn.local.tecno-fly.com/v1/volumes/{{ apps.vault.volume_name }}?action=pvcCreate"
    method: POST
    body: '{"namespace":"{{ apps.vault.namespace }}","pvcName":"{{ apps.vault.pvc_name }}"}'
    body_format: json
    validate_certs: false
  delegate_to: localhost

- name: Deploy vault
  k8s:
    state: present
    src: "{{ item }}"
  with_items:
    - '{{playbook_dir}}/k3s-apps-install/files/argocd-homelab-pi-k3s/platform/vault/project/vault.yaml'
    - '{{playbook_dir}}/k3s-apps-install/files/argocd-homelab-pi-k3s/platform/vault/application/vault.yaml'
  delegate_to: localhost

- name: Pause 1 minutes to deploy vault
  pause:
    minutes: 1

- name: Wait for vault pods to be running
  shell: kubectl get pods -n vault -o json
  register: kubectl_get_pods_vault
  until: kubectl_get_pods_vault.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  delegate_to: localhost
  retries: 10
  delay: 30

- name: Unseal vault
  shell: "kubectl exec -ti vault-0 -n vault -- vault operator unseal {{ item }}"
  with_items: "{{ apps.vault.unseal_keys }}"
  delegate_to: localhost

- name: Port-fordward vault
  shell: kubectl port-forward -n vault service/vault 8200:8200 > /dev/null 2>&1 &
  delegate_to: localhost

- name: Grant permission to argocd
  shell: vault write auth/kubernetes/config token_reviewer_jwt="`kubectl get secret argocd-repo-server -n argocd -o go-template='{{ '{{' }} .data.token {{ '}}' }}' | base64 --decode`" kubernetes_host="`kubectl config view --raw --minify --flatten --output='jsonpath={.clusters[].cluster.server}'`" kubernetes_ca_cert="`kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}' | base64 --decode`" disable_local_ca_jwt="true"
  environment:
    VAULT_ADDR: http://localhost:8200
    VAULT_SKIP_VERIFY: true
  delegate_to: localhost

- name: Get kubectl port-forward process
  shell: "ps -ef | grep -v grep | grep -w 'kubectl port-forward -n vault service/vault 8200:8200' | awk '{print $2}'"
  register: port_forward_process
  delegate_to: localhost

- name: Kill kubectl port-forward process
  shell: "kill -9 {{ item }}"
  with_items: "{{ port_forward_process.stdout_lines }}"
  delegate_to: localhost

- name: Restore longhorn backup target secret file
  lineinfile:
    dest: "{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s/system/longhorn-system/kustomization.yaml"
    regexp: "^#{{ item }}"
    line: "{{ item }}"
    state: present
  with_items:
    - '- ./secrets/longhorn-backup-target-credential-secret.yaml'
  delegate_to: localhost

- name: Commit longhorn changes to repository
  shell: |
    git add kustomization.yaml &&
    git commit -m "[Ansible] Longhorn - Restore backup target secret file" &&
    git push
  args:
    chdir: "{{playbook_dir}}/k3s-apps-install/files/homelab-pi-k3s/system/longhorn-system"
  delegate_to: localhost

- name: Deploy longhorn with vault plugin
  k8s:
    state: present
    src: "{{playbook_dir}}/k3s-apps-install/files/argocd-homelab-pi-k3s/system/longhorn-system/application/longhorn-system.yaml"
    apply: true
  delegate_to: localhost

- name: Deploy argocd deploy to argocd
  k8s:
    state: present
    src: "{{ item }}"
  with_items:
    - '{{playbook_dir}}/k3s-apps-install/files/argocd-homelab-pi-k3s/platform/argocd/project/argocd.yaml'
    - '{{playbook_dir}}/k3s-apps-install/files/argocd-homelab-pi-k3s/platform/argocd/application/argocd.yaml'
  delegate_to: localhost
