ingress:
  enabled: True

  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
    # kubernetes.io/tls-acme: "true"

  hosts:
    - host: gitea.192.168.40.200.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: gitea-tls
     hosts:
       - gitea.192.168.40.200.nip.io

persistence:
  enabled: True
  storageClass: longhorn

gitea:
  admin:
    existingSecret: gitea-admin-secret

memcached:
  enabled: True
  image:
    registry: ghcr.io
    repository: zcube/bitnami-compat/memcached
    tag: 1.6.17
  service:
    port: 11211

postgresql:
  enabled: True
  image:
    registry: ghcr.io
    repository: zcube/bitnami-compat/postgresql
    tag: 11.17.0
  persistence:
    storageClass: longhorn
