---
- name: Create "{{ argocd.namespace }}" namespace
  k8s:
    name: "{{ argocd.namespace }}"
    kind: Namespace
    state: present
  delegate_to: localhost

- name: Git checkout
  git:
    repo: "{{ argocd.repo }}"
    dest: "{{playbook_dir}}/argocd/files/homelab-pi-k3s"
  delegate_to: localhost

- name: Deploy ArgoCD
  ansible.builtin.shell: |
    helm dependency build &&
    helm template "{{ argocd.name }}" --include-crds --namespace "{{ argocd.namespace }}" . > resources/all.yaml &&
    kubectl apply -k .
  args:
    chdir: "{{playbook_dir}}/argocd/files/homelab-pi-k3s/platform/argocd/"
  delegate_to: localhost

- name: Remove repo
  ansible.builtin.file:
    path: "{{playbook_dir}}/argocd/files/homelab-pi-k3s"
    state: absent
  delegate_to: localhost