---
- name: Install k3s
  shell: curl -sfL https://get.k3s.io | sh -
  args:
    warn: false
  environment:
    INSTALL_K3S_VERSION: '{{ k3s_version }}'
    K3S_URL: 'https://{{ k3s_master.ip }}:6443'
    K3S_TOKEN: '{{ hostvars[k3s_master.hostname].k3s_node_token_encoded.content | b64decode | trim }}'
    # INSTALL_K3S_EXEC: "{{ k3s_worker.flags | join(' ') }}"
  register: k3s_agent_install

- debug: msg="{{ k3s_agent_install.stdout_lines }}"
- debug: msg="{{ k3s_agent_install.stderr_lines }}"

- name: Apply labels to each worker nodes 
  k8s: 
    state: present
    definition: 
      apiVersion: v1 
      kind: Node
      metadata:
        name: "{{ inventory_hostname }}"
        labels: 
          kubernetes.io/role: worker
  delegate_to: localhost