---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: k3s
  namespace: metallb-system
spec:
  addresses:
  - 192.168.30.201-192.168.30.254
  autoAssign: False
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: network
  namespace: metallb-system
spec:
  addresses:
  - 192.168.40.200-192.168.40.254
  autoAssign: False
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: iot
  namespace: metallb-system
spec:
  addresses:
  - 192.168.60.201-192.168.60.254
  autoAssign: False
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - k3s
  - network
  - iot
