---
- name: Add cert-manager Helm repository
  kubernetes.core.helm_repository:
    name: "{{ certManager.helm.repo_name }}"
    repo_url: "{{ certManager.helm.repo_url }}"
  delegate_to: localhost

- name: Create cert-manager values file
  template:
    src: "templates//cert-manager_values.yaml.j2"
    dest: "{{playbook_dir}}/k3s-base-apps/files/cert-manager_values.yaml"
    mode: 0644
  delegate_to: localhost

- name: Create "{{ certManager.namespace }}" namespace
  k8s:
    name: "{{ certManager.namespace }}"
    kind: Namespace
    state: present
  delegate_to: localhost

- name: Download CustomResourceDefinition for cert-manager.
  ansible.builtin.get_url:
    url: "https://github.com/jetstack/cert-manager/releases/download/v{{ certManager.version }}/cert-manager.crds.yaml"
    dest: "{{playbook_dir}}/k3s-base-apps/files/cert-manager.crds.yaml"
    mode: '0664'
  delegate_to: localhost

- name: Apply CustomResourceDefinition for cert-manager.
  k8s:
    state: present
    src: "{{playbook_dir}}/k3s-base-apps/files/cert-manager.crds.yaml"
  delegate_to: localhost

- name: Deploy latest version of CertManager chart inside "{{ certManager.namespace }}" namespace
  kubernetes.core.helm:
    name: "{{ certManager.helm.chart_name }}"
    chart_ref: "{{ certManager.helm.chart_ref }}"
    release_namespace: "{{ certManager.namespace }}"
    update_repo_cache: true
    values_files:
      - "{{playbook_dir}}/k3s-base-apps/files/cert-manager_values.yaml"
  delegate_to: localhost

- name: Create LetsEncrypts issuers config file
  template:
    src: "templates/cert-manager_issuers.yaml.j2"
    dest: "{{playbook_dir}}/k3s-base-apps/files/cert-manager_issuers.yaml"
    mode: 0644
  delegate_to: localhost

- name: Apply LetsEncrypts issuers.
  kubernetes.core.k8s:
    state: present
    src: "{{playbook_dir}}/k3s-base-apps/files/cert-manager_issuers.yaml"
  delegate_to: localhost