---
- name: Add longhorn Helm repository
  kubernetes.core.helm_repository:
    name: "{{ longhorn.helm.repo_name }}"
    repo_url: "{{ longhorn.helm.repo_url }}"
  delegate_to: localhost

- name: Create longhorn-system namespace
  k8s:
    name: "{{ longhorn.namespace }}"
    kind: Namespace
    state: present
  delegate_to: localhost

- name: Create longhorn secret file
  template:
    src: "templates/longhorn_aws-secret.yaml.j2"
    dest: "{{playbook_dir}}/k3s-base-apps/files/longhorn_aws-secret.yaml"
    mode: 0644
  delegate_to: localhost

- name: Apply secret
  k8s:
    state: present
    src: "{{playbook_dir}}/k3s-base-apps/files/longhorn_aws-secret.yaml"
  delegate_to: localhost

- name: Create longhorn config file
  template:
    src: "templates/longhorn_values.yaml.j2"
    dest: "{{playbook_dir}}/k3s-base-apps/files/longhorn_values.yaml"
    mode: 0644
  delegate_to: localhost

- name: Deploy latest version of longhorn chart inside longhorn-system namespace
  kubernetes.core.helm:
    name: "{{ longhorn.helm.chart_name }}"
    chart_ref: "{{ longhorn.helm.chart_ref }}"
    release_namespace: "{{ longhorn.namespace }}"
    update_repo_cache: true
    values_files:
      - "{{playbook_dir}}/k3s-base-apps/files/longhorn_values.yaml"
  delegate_to: localhost

- name: Set longhorn as only default storageClass (disable default of local-path)
  k8s:
    state: present
    kind: StorageClass
    name: local-path
    definition:
      metadata:
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
  delegate_to: localhost

- name: Create longhorn recurring jos file
  template:
    src: "templates/longhorn_recurring-jobs.yaml.j2"
    dest: "{{playbook_dir}}/k3s-base-apps/files/longhorn_recurring-jobs.yaml"
    mode: 0644
  delegate_to: localhost

- name: Apply Longhorn recurring jos
  k8s:
    state: present
    src: "{{playbook_dir}}/k3s-base-apps/files/longhorn_recurring-jobs.yaml"
  delegate_to: localhost

# TODO: https://www.bookstack.cn/read/longhorn-1.1.1-en/5608169f6e00ab9c.md